/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMembershipManager,
  IMembershipManagerInterface,
} from "../../interfaces/IMembershipManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMembershipManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMembershipManagerInterface {
    return new Interface(_abi) as IMembershipManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMembershipManager {
    return new Contract(address, _abi, runner) as unknown as IMembershipManager;
  }
}
