/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IListingManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blockInterval"
      | "getListing"
      | "getListingOwner"
      | "getListingPricePerHour"
      | "isAvailable"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "blockInterval",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListingOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListingPricePerHour",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAvailable",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "blockInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getListingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingPricePerHour",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
}

export interface IListingManager extends BaseContract {
  connect(runner?: ContractRunner | null): IListingManager;
  waitForDeployment(): Promise<this>;

  interface: IListingManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blockInterval: TypedContractMethod<
    [listingId: BigNumberish, startTs: BigNumberish, endTs: BigNumberish],
    [void],
    "nonpayable"
  >;

  getListing: TypedContractMethod<
    [listingId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        owner: string;
        pricePerHour: bigint;
        metadataCID: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getListingOwner: TypedContractMethod<
    [listingId: BigNumberish],
    [string],
    "view"
  >;

  getListingPricePerHour: TypedContractMethod<
    [listingId: BigNumberish],
    [bigint],
    "view"
  >;

  isAvailable: TypedContractMethod<
    [listingId: BigNumberish, startTs: BigNumberish, endTs: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blockInterval"
  ): TypedContractMethod<
    [listingId: BigNumberish, startTs: BigNumberish, endTs: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        owner: string;
        pricePerHour: bigint;
        metadataCID: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getListingOwner"
  ): TypedContractMethod<[listingId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getListingPricePerHour"
  ): TypedContractMethod<[listingId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAvailable"
  ): TypedContractMethod<
    [listingId: BigNumberish, startTs: BigNumberish, endTs: BigNumberish],
    [boolean],
    "view"
  >;

  filters: {};
}
