/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessNFT__factory>;
    getContractFactory(
      name: "BookingManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BookingManager__factory>;
    getContractFactory(
      name: "IAccessNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessNFT__factory>;
    getContractFactory(
      name: "IListingManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IListingManager__factory>;
    getContractFactory(
      name: "IMembershipManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMembershipManager__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ListingManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ListingManager__factory>;
    getContractFactory(
      name: "MembershipManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MembershipManager__factory>;

    getContractAt(
      name: "AccessNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessNFT>;
    getContractAt(
      name: "BookingManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BookingManager>;
    getContractAt(
      name: "IAccessNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessNFT>;
    getContractAt(
      name: "IListingManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IListingManager>;
    getContractAt(
      name: "IMembershipManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMembershipManager>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ListingManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ListingManager>;
    getContractAt(
      name: "MembershipManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MembershipManager>;

    deployContract(
      name: "AccessNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessNFT>;
    deployContract(
      name: "BookingManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BookingManager>;
    deployContract(
      name: "IAccessNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessNFT>;
    deployContract(
      name: "IListingManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IListingManager>;
    deployContract(
      name: "IMembershipManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMembershipManager>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ListingManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ListingManager>;
    deployContract(
      name: "MembershipManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MembershipManager>;

    deployContract(
      name: "AccessNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessNFT>;
    deployContract(
      name: "BookingManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BookingManager>;
    deployContract(
      name: "IAccessNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessNFT>;
    deployContract(
      name: "IListingManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IListingManager>;
    deployContract(
      name: "IMembershipManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMembershipManager>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ListingManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ListingManager>;
    deployContract(
      name: "MembershipManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MembershipManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
